{
  "formatVersion": "1.1",
  "component": {
    "url": "../../task-viewer/5.0.1/task-viewer-5.0.1.module",
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-wasm-js.klib",
          "url": "task-viewer-wasm-js-5.0.1.klib",
          "size": 75677,
          "sha512": "32fbd383074faa2ae940c0c01dba7a7aacb105c558d5ed4e20572b94faf5efd57b593404eddb5bc77c4f00929421b7c872601eeb367e72212bd47d4b830a2ad7",
          "sha256": "f763db9efb6a8970d243c55652af576ab21d73f7f3c45c9400df15b6b619c4ed",
          "sha1": "3033f58df3e21a26f7bc4f53146635f28aac2609",
          "md5": "fa2395ebbc3cd9923087c4ae20281d7f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-wasm-js.klib",
          "url": "task-viewer-wasm-js-5.0.1.klib",
          "size": 75677,
          "sha512": "32fbd383074faa2ae940c0c01dba7a7aacb105c558d5ed4e20572b94faf5efd57b593404eddb5bc77c4f00929421b7c872601eeb367e72212bd47d4b830a2ad7",
          "sha256": "f763db9efb6a8970d243c55652af576ab21d73f7f3c45c9400df15b6b619c4ed",
          "sha1": "3033f58df3e21a26f7bc4f53146635f28aac2609",
          "md5": "fa2395ebbc3cd9923087c4ae20281d7f"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "task-viewer-wasm-js-sources.jar",
          "url": "task-viewer-wasm-js-5.0.1-sources.jar",
          "size": 7737,
          "sha512": "6fbc513b92dd7b1192e526732e1b8f27d7da90fe01a45ad0d8ccd5d59e2295bd0d57843d32afbddf771d4ffbbd440e6a6359d8ac5ecb0bbedc1ac91f996920d7",
          "sha256": "a390d577517443d693833cb17a3d74cf9bdf0b6bb8310d7fe562c0ded71263ad",
          "sha1": "0c3522f3d689b94074837919f5fef656ad85e103",
          "md5": "86d6d0444327fc64e985b40bba082d48"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer.kotlin_resources.zip",
          "url": "task-viewer-wasm-js-5.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 358,
          "sha512": "e8631fde54ac384e21c31623d68b8e689485dc9d52c1c1d237a46631f70e25b858761de1f3917302df5a7c2bdef626a00c1c200e0bfce725a4ae621dbdc99c7a",
          "sha256": "d206d2f4490ee4510a277d1949321ec46d39ca83aaf2c4f724217395f82a700d",
          "sha1": "94b1fd05774a0c5b4b8a3d70761117039316c09e",
          "md5": "b879323c8503ac701f0a8644cfa062d8"
        }
      ]
    }
  ]
}
