{
  "formatVersion": "1.1",
  "component": {
    "url": "../../task-viewer/5.0.1/task-viewer-5.0.1.module",
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-jvm.jar",
          "url": "task-viewer-jvm-5.0.1.jar",
          "size": 71837,
          "sha512": "68bf324ad93beec0175d3b9e7a9867940acfe234c586c2e29cfd1915d7f3b3a557c4e13f0cd46ea7d858842743370a2090fcb8b8e69d7b91ed867e4f7b087348",
          "sha256": "915d7b3c9a53990bd4bb7b46f53e7ba7cb1b04ebc35ecd899b60ab2d441fa1bf",
          "sha1": "e7d19f6e5fdfd9abfd71dfb97e7380cf6f9b0f99",
          "md5": "7ba4d4f88df2d0aaa7a4d22284ff0162"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-jvm.jar",
          "url": "task-viewer-jvm-5.0.1.jar",
          "size": 71837,
          "sha512": "68bf324ad93beec0175d3b9e7a9867940acfe234c586c2e29cfd1915d7f3b3a557c4e13f0cd46ea7d858842743370a2090fcb8b8e69d7b91ed867e4f7b087348",
          "sha256": "915d7b3c9a53990bd4bb7b46f53e7ba7cb1b04ebc35ecd899b60ab2d441fa1bf",
          "sha1": "e7d19f6e5fdfd9abfd71dfb97e7380cf6f9b0f99",
          "md5": "7ba4d4f88df2d0aaa7a4d22284ff0162"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "task-viewer-jvm-sources.jar",
          "url": "task-viewer-jvm-5.0.1-sources.jar",
          "size": 7737,
          "sha512": "6fbc513b92dd7b1192e526732e1b8f27d7da90fe01a45ad0d8ccd5d59e2295bd0d57843d32afbddf771d4ffbbd440e6a6359d8ac5ecb0bbedc1ac91f996920d7",
          "sha256": "a390d577517443d693833cb17a3d74cf9bdf0b6bb8310d7fe562c0ded71263ad",
          "sha1": "0c3522f3d689b94074837919f5fef656ad85e103",
          "md5": "86d6d0444327fc64e985b40bba082d48"
        }
      ]
    }
  ]
}
