{
  "formatVersion": "1.1",
  "component": {
    "url": "../../app-shared/6.0.2/app-shared-6.0.2.module",
    "group": "io.github.mflisar.toolbox",
    "module": "app-shared",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "storage-keyvalue",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-navigator",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-transitions",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-screenmodel",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui-adaptive",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "backup",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-console",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "extension-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared-wasm-js.klib",
          "url": "app-shared-wasm-js-6.0.2.klib",
          "size": 696854,
          "sha512": "487906aa173ed3a35e9103a44012620c011fdbaa1cf479bc09881725f2c959e8e0476759402e404afa78398e5adfa379a9fbe4fdedec76e194785d6afbc7b2e3",
          "sha256": "8ad2e399296bdd0bcea346b994ef9f8e880cf1b934e31496f605309e10eea17b",
          "sha1": "7aff491400f730f0f92bce825e1bdf65f3e80d17",
          "md5": "52c5fbcb9b53c287fb22983ce63b559d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "storage-keyvalue",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-navigator",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-transitions",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-screenmodel",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui-adaptive",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "backup",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-console",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "extension-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "br.com.devsrsouza.compose.icons",
          "module": "font-awesome",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "renderer-header",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "statesaver-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-time",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-bool",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-list",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-button",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "kotpreferences",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composecolors",
          "module": "material",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-picker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-defaultpicker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-wasm-js.klib",
          "url": "app-shared-wasm-js-6.0.2.klib",
          "size": 696854,
          "sha512": "487906aa173ed3a35e9103a44012620c011fdbaa1cf479bc09881725f2c959e8e0476759402e404afa78398e5adfa379a9fbe4fdedec76e194785d6afbc7b2e3",
          "sha256": "8ad2e399296bdd0bcea346b994ef9f8e880cf1b934e31496f605309e10eea17b",
          "sha1": "7aff491400f730f0f92bce825e1bdf65f3e80d17",
          "md5": "52c5fbcb9b53c287fb22983ce63b559d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "shared-wasm-js-sources.jar",
          "url": "app-shared-wasm-js-6.0.2-sources.jar",
          "size": 107633,
          "sha512": "0d420d200dced349967b756e13d683570f42a7fab42646057a28a7e887ab39404260da0382cc66c22057a3a3096d1ba26c2fce0b77579feec6d38a343e09c648",
          "sha256": "51c538199d00657f4f02b44bcb99c964bb06244fceac422b2971047762da064a",
          "sha1": "e022ce9e9f0000266728bcc6691a85dd741d9b1a",
          "md5": "9e5a7a0e097cff5bfb9d6ce3b05fa4ac"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "storage-keyvalue",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-navigator",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-transitions",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-screenmodel",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui-adaptive",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "backup",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-console",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "extension-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "br.com.devsrsouza.compose.icons",
          "module": "font-awesome",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "renderer-header",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "statesaver-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-time",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-bool",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-list",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-button",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "kotpreferences",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composecolors",
          "module": "material",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-picker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-defaultpicker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared.kotlin_resources.zip",
          "url": "app-shared-wasm-js-6.0.2-kotlin_resources.kotlin_resources.zip",
          "size": 340,
          "sha512": "7eb504ab3aeaf793f4c4982105f94fc68f8ef5f5799ec4eed542b0327beb0f18419bb66307f54e70181bcc0664354cecc6916d35710a2578883bef5f3dcd70ca",
          "sha256": "075dab21cd8642d12626c34a92502a887a0c183471058be6bdc216c56c0e2512",
          "sha1": "e5dd2d1e97b6652c55c653a84a6ddf82a202121b",
          "md5": "2124854f8164edf6d5579677223977e2"
        }
      ]
    }
  ]
}
