{
  "formatVersion": "1.1",
  "component": {
    "url": "../../task-viewer/5.0.0/task-viewer-5.0.0.module",
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-iosArm64Main.klib",
          "url": "task-viewer-iosarm64-5.0.0.klib",
          "size": 61845,
          "sha512": "0ec1686a4cbd8c622fd49a769e6d82144116adcafaf5eb2396aadfa35197a805021f080739f57950b3e2e259b6f0666b39fb86e440f2509d137c0796ccf7d423",
          "sha256": "ef02c716ea8f377bce7af6d80d4ab35f192e89e6c37cf5c3768371017d9197b0",
          "sha1": "81a722bcb9efc57de243c3b4738d0e3d2a0e8d55",
          "md5": "6c260e82d507e27e3b721a55159b1248"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "task-viewer-iosarm64-sources.jar",
          "url": "task-viewer-iosarm64-5.0.0-sources.jar",
          "size": 6631,
          "sha512": "e37e3132c61c22141f17923f6c21097bf2d0023f70dda5d77a205625e28cda6ba12f4e0eb4fcddc8b1fbd4799726d4d6357cd3918077358492712a7ed19a7fd1",
          "sha256": "4951a73b751f31100acce2a3eb3cde785bf4e9e427d2e357c38271ee46d4b209",
          "sha1": "30966c6c3fec53e973f720b1ab5ba6ceb681f424",
          "md5": "22a72a162b280e719bb256c04e8fcab9"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer.kotlin_resources.zip",
          "url": "task-viewer-iosarm64-5.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 358,
          "sha512": "e8631fde54ac384e21c31623d68b8e689485dc9d52c1c1d237a46631f70e25b858761de1f3917302df5a7c2bdef626a00c1c200e0bfce725a4ae621dbdc99c7a",
          "sha256": "d206d2f4490ee4510a277d1949321ec46d39ca83aaf2c4f724217395f82a700d",
          "sha1": "94b1fd05774a0c5b4b8a3d70761117039316c09e",
          "md5": "b879323c8503ac701f0a8644cfa062d8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-iosarm64-metadata.jar",
          "url": "task-viewer-iosarm64-5.0.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
