{
  "formatVersion": "1.1",
  "component": {
    "url": "../../task-viewer/6.0.6/task-viewer-6.0.6.module",
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "6.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer.aar",
          "url": "task-viewer-android-6.0.6.aar",
          "size": 186477,
          "sha512": "6cecac2814040dc5d99d5c649efba0529f421812c23b1ef359df309b65070a5707092dbfcea8dd3c7a876d57ec9132c4389e43112eba2aeaa8aca4a7aa47bae5",
          "sha256": "f2d6753784837568a68a12b83967372635d31ec5a6115949246fbd86ea739093",
          "sha1": "39323b1cf6cba7119b726b6d0873b09ca4c46785",
          "md5": "0f372adc338f4ab0680d3d6cdb3e1df0"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer.aar",
          "url": "task-viewer-android-6.0.6.aar",
          "size": 186477,
          "sha512": "6cecac2814040dc5d99d5c649efba0529f421812c23b1ef359df309b65070a5707092dbfcea8dd3c7a876d57ec9132c4389e43112eba2aeaa8aca4a7aa47bae5",
          "sha256": "f2d6753784837568a68a12b83967372635d31ec5a6115949246fbd86ea739093",
          "sha1": "39323b1cf6cba7119b726b6d0873b09ca4c46785",
          "md5": "0f372adc338f4ab0680d3d6cdb3e1df0"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "task-viewer-android-sources.jar",
          "url": "task-viewer-android-6.0.6-sources.jar",
          "size": 21322,
          "sha512": "0bd86719daf36bc8a72d1099c4e6c4c272d05b0d60996a685691ece8c6bfe62fdb7fd3e416a8353a342708ed6a58914965072e97fe2c50a987dd1a7aad7e1160",
          "sha256": "1393f44a9ab41bcdd3095cdbd967cdb19381b34d460e9d981d27194733920ef4",
          "sha1": "88dca27354de01cb0512926b159938b14cf4aabb",
          "md5": "7dbe20f6c1ab2e0dc35ca3dfc77919d3"
        }
      ]
    }
  ]
}
