{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui/6.0.3/ui-6.0.3.module",
    "group": "io.github.mflisar.toolbox",
    "module": "ui",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui.aar",
          "url": "ui-android-6.0.3.aar",
          "size": 843041,
          "sha512": "6700c4433f8375ed388a491c90a685e9ead4b7f9331ff761afa1571e90c20a659c24f087ea03f28d6ecaa60c5b7ed9bbb9f2d8c1b07bbc0d49d6be9dc5c831ae",
          "sha256": "cf0aa47e85865493b81175b9bfd8aff56f7726e53fa804ab9e2f2b5796a55b8a",
          "sha1": "5b19dbd58ce02134cef2662eb12db9ebf58f5896",
          "md5": "fe60cd796788560ce3507d2706bc3b02"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui.aar",
          "url": "ui-android-6.0.3.aar",
          "size": 843041,
          "sha512": "6700c4433f8375ed388a491c90a685e9ead4b7f9331ff761afa1571e90c20a659c24f087ea03f28d6ecaa60c5b7ed9bbb9f2d8c1b07bbc0d49d6be9dc5c831ae",
          "sha256": "cf0aa47e85865493b81175b9bfd8aff56f7726e53fa804ab9e2f2b5796a55b8a",
          "sha1": "5b19dbd58ce02134cef2662eb12db9ebf58f5896",
          "md5": "fe60cd796788560ce3507d2706bc3b02"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-android-sources.jar",
          "url": "ui-android-6.0.3-sources.jar",
          "size": 81016,
          "sha512": "ec9067aa558377bd10a57bdbb1b81b14907c881ab4d7217d050bd89ef82f579481db61443f87c4d50863886cf6c8bcd6b6b84b64fdf8a1739898826bab6081bf",
          "sha256": "29d077da3922897938883905b9b580756d106c5c8c66b14b4e7792781c4b5480",
          "sha1": "d2a6a1934c0bed47df7567ea54bd8d662baaca75",
          "md5": "2b6c58815fa55ca7c73c365d4361ef83"
        }
      ]
    }
  ]
}
