{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-metadata.jar",
          "url": "task-viewer-6.0.2.jar",
          "size": 14220,
          "sha512": "57b7a11d1e4e74e5046e0f37b4443a8f1ed4516967d7d6b966b328a293f951609e495cc750a782224142be513831d2ce4b0f15b7bd303d573553f371b53efc2a",
          "sha256": "a60c3132152489d0d23e195b0a6170424435166869bbaf6fac543ca2329cdc22",
          "sha1": "477f302254766034ee60e06dc39b828016e3fb1a",
          "md5": "8c0ee0ea49f2e45f6440e58d3e8aec45"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "task-viewer-kotlin-sources.jar",
          "url": "task-viewer-6.0.2-sources.jar",
          "size": 14883,
          "sha512": "766b2084bfac22b51a6db190e588d9e0c7788c1a34e14469069e33ecf5f1f047f88eed5e0940c408777e39823f9dfaa3af186da44a8ea76ba26016d6a7181482",
          "sha256": "25bfa932cb28fb2d2ac610df9b52f988ea9ff677351ef2a88a5ec6e969b478f3",
          "sha1": "980cd4b2a3f21522b882b389d4aa71f73a6fac3b",
          "md5": "8b335ed761aecc6bce91bcdfda37a0ea"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../task-viewer-android/6.0.2/task-viewer-android-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-android",
        "version": "6.0.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../task-viewer-android/6.0.2/task-viewer-android-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-android",
        "version": "6.0.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../task-viewer-android/6.0.2/task-viewer-android-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-android",
        "version": "6.0.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/6.0.2/task-viewer-iosarm64-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "6.0.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/6.0.2/task-viewer-iosarm64-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "6.0.2"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/6.0.2/task-viewer-iosarm64-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "6.0.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/6.0.2/task-viewer-iosarm64-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "6.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/6.0.2/task-viewer-iossimulatorarm64-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "6.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/6.0.2/task-viewer-iossimulatorarm64-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "6.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/6.0.2/task-viewer-iossimulatorarm64-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "6.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/6.0.2/task-viewer-iossimulatorarm64-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "6.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../task-viewer-jvm/6.0.2/task-viewer-jvm-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-jvm",
        "version": "6.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../task-viewer-jvm/6.0.2/task-viewer-jvm-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-jvm",
        "version": "6.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../task-viewer-jvm/6.0.2/task-viewer-jvm-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-jvm",
        "version": "6.0.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/6.0.2/task-viewer-wasm-js-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "6.0.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/6.0.2/task-viewer-wasm-js-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "6.0.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/6.0.2/task-viewer-wasm-js-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "6.0.2"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/6.0.2/task-viewer-wasm-js-6.0.2.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "6.0.2"
      }
    }
  ]
}
