{
  "formatVersion": "1.1",
  "component": {
    "url": "../../app-shared/5.0.0/app-shared-5.0.0.module",
    "group": "io.github.mflisar.toolbox",
    "module": "app-shared",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-navigator",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-transitions",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-screenmodel",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui-adaptive",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "backup",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-console",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "extension-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-file",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "storage-datastore",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "br.com.devsrsouza.compose.icons",
          "module": "font-awesome",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "renderer-header",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "statesaver-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-time",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-bool",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-list",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-button",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "kotpreferences",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composecolors",
          "module": "material",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-picker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-defaultpicker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "extension-composeviewer",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-lumberjack",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosArm64Main.klib",
          "url": "app-shared-iosarm64-5.0.0.klib",
          "size": 652194,
          "sha512": "a2a6d547ab1783b8cfd2762e5739d60e951335d4e9d7f520279429a14d49062dbf5b80b908605058816382c4d5e84ec20ebd403a6540644d7a3a4accc99cdb15",
          "sha256": "8e6d9a0c9a2c0ef0c98cd19efda5b125b1a28aef0af65b15f284a404416352f0",
          "sha1": "fd62f0ddea64a1987823aa92fc3408ec08c66a70",
          "md5": "8e0751eb308b643278b2aef083ef6108"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "shared-iosarm64-sources.jar",
          "url": "app-shared-iosarm64-5.0.0-sources.jar",
          "size": 105182,
          "sha512": "07fbd1c66795de4c864000b6bdfcdb5f3fe4617ae12ba6683871781d4207eb423731d5077096da0e8b71e96d7bbdfee332dd133bf719fffed488891719cc1146",
          "sha256": "ba6f029e4907224ae220caf2a588fdd1105c1310920132074311b436efd0894b",
          "sha1": "082a6bff31c61665b09926e6db7fae32ee8dd8de",
          "md5": "47ddd8667aeb7a5d4c05c5d04d3159af"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-navigator",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-transitions",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-screenmodel",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui-adaptive",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "backup",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-console",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "extension-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-file",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "storage-datastore",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "br.com.devsrsouza.compose.icons",
          "module": "font-awesome",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "renderer-header",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "statesaver-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-time",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-bool",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-list",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-button",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "kotpreferences",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composecolors",
          "module": "material",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-picker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-defaultpicker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "extension-composeviewer",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-lumberjack",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared.kotlin_resources.zip",
          "url": "app-shared-iosarm64-5.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 340,
          "sha512": "7eb504ab3aeaf793f4c4982105f94fc68f8ef5f5799ec4eed542b0327beb0f18419bb66307f54e70181bcc0664354cecc6916d35710a2578883bef5f3dcd70ca",
          "sha256": "075dab21cd8642d12626c34a92502a887a0c183471058be6bdc216c56c0e2512",
          "sha1": "e5dd2d1e97b6652c55c653a84a6ddf82a202121b",
          "md5": "2124854f8164edf6d5579677223977e2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-navigator",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-transitions",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-screenmodel",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui-adaptive",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "backup",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-console",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "extension-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-file",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "storage-datastore",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "br.com.devsrsouza.compose.icons",
          "module": "font-awesome",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "renderer-header",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "statesaver-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-time",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-bool",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-list",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-button",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "kotpreferences",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composecolors",
          "module": "material",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-picker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-defaultpicker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "extension-composeviewer",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-lumberjack",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosarm64-metadata.jar",
          "url": "app-shared-iosarm64-5.0.0-metadata.jar",
          "size": 4351,
          "sha512": "01aa9c93e8b5f6d00d77e8fc17cd59cd5f0ff6e9726341c94ec984f1706a745848fc1b1f8cfe574271e7db711ad38d390687d5413545649cf10b2a45a33ea5e6",
          "sha256": "b658214c919e66a596122d564194b707cfa5798bf5e3fa137d29794f2fd6dac9",
          "sha1": "906af1e9ac85b35a5389da37174f9beab4ca1690",
          "md5": "04a36d507f2cde868a1185efd553717d"
        }
      ]
    }
  ]
}
