{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/6.0.6/core-6.0.6.module",
    "group": "io.github.mflisar.toolbox",
    "module": "core",
    "version": "6.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpplatformcontext",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "core-jvm-6.0.6.jar",
          "size": 185871,
          "sha512": "e4d1d6ef926e1f2f068f9775d0bb7897e8a3e7a6c7ee79303ce6cdf05555edbb5a17b899ae5297efe9bb2df35d40c5344017e4ae434ea95422c1c9ecbc7cf756",
          "sha256": "a58e5e38539c7fceb2db45e32ae621047f67efff0089d940693c13302544c316",
          "sha1": "02439bf569011ba0c42c050631a502cf3879a8ba",
          "md5": "e7a6cea25361d240cb5173e0eb168343"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpplatformcontext",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "core-jvm-6.0.6.jar",
          "size": 185871,
          "sha512": "e4d1d6ef926e1f2f068f9775d0bb7897e8a3e7a6c7ee79303ce6cdf05555edbb5a17b899ae5297efe9bb2df35d40c5344017e4ae434ea95422c1c9ecbc7cf756",
          "sha256": "a58e5e38539c7fceb2db45e32ae621047f67efff0089d940693c13302544c316",
          "sha1": "02439bf569011ba0c42c050631a502cf3879a8ba",
          "md5": "e7a6cea25361d240cb5173e0eb168343"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-sources.jar",
          "url": "core-jvm-6.0.6-sources.jar",
          "size": 39178,
          "sha512": "d47a2d5fa929cfa5e986e9dd2e86f5949632dbe880812e7683f9249bc82cc4668b50bfb619d228d610872b468fc1d45461528a989d12f55818aa709853a77ef9",
          "sha256": "6c5176c485b1008d5024b68d246e6878398d006763d0b6c3f64515e4ad6a4b01",
          "sha1": "58a5ea94c296f534661c9f81b8a98657478efc75",
          "md5": "5675e834b16d3ef3363deb369abd7a76"
        }
      ]
    }
  ]
}
