{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/5.0.1/core-5.0.1.module",
    "group": "io.github.mflisar.toolbox",
    "module": "core",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpplatformcontext",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpmail",
          "module": "library",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "extension-feedback",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosArm64Main.klib",
          "url": "core-iosarm64-5.0.1.klib",
          "size": 186197,
          "sha512": "8c3ab7a9cf1354563e786840607f214a2cf17661bb7cbc473b8dd7a9568c215d4d55d275c04f11ee96682e7593382d058e55625c28cec1a1390ce3bb3de34a9b",
          "sha256": "f2cf4d3b095ec368bc9797b5be282a1678c7d193fbcb3dd9e1339a98c11f3fda",
          "sha1": "5fbefe1b9a96bc626715121a09ac435c867850ef",
          "md5": "814d89ed02cac3f139e04287ad3f9fdb"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosarm64-sources.jar",
          "url": "core-iosarm64-5.0.1-sources.jar",
          "size": 37542,
          "sha512": "66b2037aa5f8dbf7aad5d4143ce892e2cb36c3f51e9a68155e0bafa76ff9b8c9216a377371f5de471f89ef2207dbd6693304e3a3accf075c50d7567bab3945a7",
          "sha256": "6ef002592013684e20639edb84d5cb6ea38ebb485bb0548f7846e352e66b1df0",
          "sha1": "51e0e791dbee0700e427f5f5fdf379eff6d2a1e2",
          "md5": "b38b2df7bb86f367de4191600538bdda"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpplatformcontext",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpmail",
          "module": "library",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "extension-feedback",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core.kotlin_resources.zip",
          "url": "core-iosarm64-5.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 6184,
          "sha512": "0a0d75e41d47373e25b78b2ec9b19e623614b454cd93d676cb0c43066dc7a99d88fd115ef8def90870cfe5d5e4a5830bcdd34ffe814e5183e4890ad1aefe0d5e",
          "sha256": "27d17d78661bf9de467f17f7ce7bfcdcc5758154260f69a631afdc5c5b287334",
          "sha1": "40b00db553b809d8d5c7ca5305c115e047d99d20",
          "md5": "01cdb15d34a350914fdf21f9688038c6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpplatformcontext",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpmail",
          "module": "library",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "extension-feedback",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-metadata.jar",
          "url": "core-iosarm64-5.0.1-metadata.jar",
          "size": 3268,
          "sha512": "0f64304a7ef44755755d4d6e82673a0aec2fc3bec72cc396f9b9dced99c104a259a7fa2e26802b621f24e20430052e12bacfb976405afc64a195fe911c7489f4",
          "sha256": "8555d42e0d4778c187757fae2379522f1e72025cc848865772978a127c3a6682",
          "sha1": "7c54bd7f6002ed1646663b4e596c07a2478b25e3",
          "md5": "211d1c89c65322b1936eaf6af572475f"
        }
      ]
    }
  ]
}
