{
  "formatVersion": "1.1",
  "component": {
    "url": "../../task-viewer/5.0.0/task-viewer-5.0.0.module",
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-jvm.jar",
          "url": "task-viewer-jvm-5.0.0.jar",
          "size": 73864,
          "sha512": "40c289b8c6453dc11140e915fce3afe9a88cafa77e48c9ba09f2192d282b2e559cd04ac15f65522eb2898f2b7f39f8392aefa76acb90f10cf528b14fe8ae16b9",
          "sha256": "fd264ab2b61f2ffaf4a6d033a056a7d9aa01dd063475a5be26b0903430bd2b83",
          "sha1": "2924fdfa36c9d29777155e663fcd02f3c0dada18",
          "md5": "a4a2d7d46696ae528c08d7909a40b3a5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-jvm.jar",
          "url": "task-viewer-jvm-5.0.0.jar",
          "size": 73864,
          "sha512": "40c289b8c6453dc11140e915fce3afe9a88cafa77e48c9ba09f2192d282b2e559cd04ac15f65522eb2898f2b7f39f8392aefa76acb90f10cf528b14fe8ae16b9",
          "sha256": "fd264ab2b61f2ffaf4a6d033a056a7d9aa01dd063475a5be26b0903430bd2b83",
          "sha1": "2924fdfa36c9d29777155e663fcd02f3c0dada18",
          "md5": "a4a2d7d46696ae528c08d7909a40b3a5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "task-viewer-jvm-sources.jar",
          "url": "task-viewer-jvm-5.0.0-sources.jar",
          "size": 6631,
          "sha512": "e37e3132c61c22141f17923f6c21097bf2d0023f70dda5d77a205625e28cda6ba12f4e0eb4fcddc8b1fbd4799726d4d6357cd3918077358492712a7ed19a7fd1",
          "sha256": "4951a73b751f31100acce2a3eb3cde785bf4e9e427d2e357c38271ee46d4b209",
          "sha1": "30966c6c3fec53e973f720b1ab5ba6ceb681f424",
          "md5": "22a72a162b280e719bb256c04e8fcab9"
        }
      ]
    }
  ]
}
