{
  "formatVersion": "1.1",
  "component": {
    "url": "../../backup/5.0.1/backup-5.0.1.module",
    "group": "io.github.mflisar.toolbox",
    "module": "backup",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "backup-iosSimulatorArm64Main.klib",
          "url": "backup-iossimulatorarm64-5.0.1.klib",
          "size": 23175,
          "sha512": "e66deeabd4d624827bf282240cf1cf5082f88ee7356ceb016e7f915e83a5b9c45d74af702da671fbc63742f3ec008a6daac3f2b3403b66f76b6e49420bb1d7ee",
          "sha256": "f3e347c2062a1166ea1c946a465a30a4a047cefa0314f4b50fd95604f4ee6104",
          "sha1": "66ea7d7170b7ca422f32e3e5336741e43a78f80b",
          "md5": "38f73ee3e34ae1b0cf75e14fc1c8f5fe"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "backup-iossimulatorarm64-sources.jar",
          "url": "backup-iossimulatorarm64-5.0.1-sources.jar",
          "size": 7600,
          "sha512": "cd8ec0ae73cf3dfae2538d385a1bdbef36653d44eabc4088b78c6ea58b68bd8d74863089f3055a12274678574bffb6b7399c1263a4c18505161b07cd0cfbe374",
          "sha256": "f0916771de4795e5c6b3e83732cfc86275afe9a3bbf44d916af62f6627f7b24d",
          "sha1": "286e43f03d565a0f46da338dea34503c26f81aab",
          "md5": "e76391b791d131b76f9ed0a44ca92cce"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "backup.kotlin_resources.zip",
          "url": "backup-iossimulatorarm64-5.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 348,
          "sha512": "f50e6df58142c4a1d5461931d6ba7c95e99639862edfe5ad27d3df1f2e10b509f8b9e8dc5071a288840525557f3fef008278acf062df5218cedafd87291011ad",
          "sha256": "19da9927ca50ea764cd6b2bd594d935cd37af7a2c96149e032dafac27756c3ca",
          "sha1": "53ea36203fe6c797bf986dc06562caac096ae1bc",
          "md5": "b4caaf036cadbe473d300b1d8d3acd50"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "backup-iossimulatorarm64-metadata.jar",
          "url": "backup-iossimulatorarm64-5.0.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
