{
  "formatVersion": "1.1",
  "component": {
    "url": "../../table/6.0.2/table-6.0.2.module",
    "group": "io.github.mflisar.toolbox",
    "module": "table",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "table-wasm-js.klib",
          "url": "table-wasm-js-6.0.2.klib",
          "size": 225867,
          "sha512": "4ce5bd3c421df823c2e85fb1bef93307e3c24a584e8e338bd6597c182d7bfc9a1f49b13fc9c0f6ce622e40e0c2a80092719d114cfa721dc7e2b38199074e9acc",
          "sha256": "17cb2747e458089e0f91312d820276ba2b2f4e91119d63793032cc2ad7e55686",
          "sha1": "bb1adb817cc55f8cfb75bcea4581a3f9a612c88d",
          "md5": "c1c80c842898db4490acfff17365cbae"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "table-wasm-js.klib",
          "url": "table-wasm-js-6.0.2.klib",
          "size": 225867,
          "sha512": "4ce5bd3c421df823c2e85fb1bef93307e3c24a584e8e338bd6597c182d7bfc9a1f49b13fc9c0f6ce622e40e0c2a80092719d114cfa721dc7e2b38199074e9acc",
          "sha256": "17cb2747e458089e0f91312d820276ba2b2f4e91119d63793032cc2ad7e55686",
          "sha1": "bb1adb817cc55f8cfb75bcea4581a3f9a612c88d",
          "md5": "c1c80c842898db4490acfff17365cbae"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "table-wasm-js-sources.jar",
          "url": "table-wasm-js-6.0.2-sources.jar",
          "size": 24264,
          "sha512": "39d668c21b66785b227ce8833c02ac245743349632af46aa4f8020148576c37c48eb08726596c97009019626d6d793a0fd95fb2d53a51a1dabeba511faf1c99e",
          "sha256": "dbb5e9d19baad37f94175c8ca35fb4e7dc8899c3e87ec430a3a70ce696032073",
          "sha1": "ba5221f7d2719d6b9d6d09660a086d1e8ce531d7",
          "md5": "26b3c80fc9010443edfec46ee9446f79"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "table.kotlin_resources.zip",
          "url": "table-wasm-js-6.0.2-kotlin_resources.kotlin_resources.zip",
          "size": 346,
          "sha512": "d58d0874c54a28ada689cb42b26bd932e86cac751cdae25f8291796af20e2ad67a464496b1b800dc30928f8d60538b5c8c3bd50580308862672a9ca41135b7d0",
          "sha256": "e7dc3df8c40038e93a5cb9f8f11e8a09b944eccbb0d88452f24327a2b49d0bbe",
          "sha1": "9785a31570d6ac4291f9276203d3d656d3e009e4",
          "md5": "974b9699512cc3dd0e02fc8578a03bf8"
        }
      ]
    }
  ]
}
