{
  "formatVersion": "1.1",
  "component": {
    "url": "../../task-viewer/6.0.5/task-viewer-6.0.5.module",
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "6.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.5"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.5"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer.aar",
          "url": "task-viewer-android-6.0.5.aar",
          "size": 183400,
          "sha512": "a7ecf4581564a65c612e106a28b6ce7f330a2e1eb180f3b4888809e2dc462ed7a93927b72e8518f32d3fe065d09c34a8a6243bbb0a53ec682495708859eef5e2",
          "sha256": "48cf5d508b6966ecdf052baad355d6bbc35be75623c6e41d5bc2045d5ac63979",
          "sha1": "57945616529895d9bbee3b1b15612ab8923acf86",
          "md5": "11df0b5493caf63acea5b9b0d4b6431b"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.5"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.5"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer.aar",
          "url": "task-viewer-android-6.0.5.aar",
          "size": 183400,
          "sha512": "a7ecf4581564a65c612e106a28b6ce7f330a2e1eb180f3b4888809e2dc462ed7a93927b72e8518f32d3fe065d09c34a8a6243bbb0a53ec682495708859eef5e2",
          "sha256": "48cf5d508b6966ecdf052baad355d6bbc35be75623c6e41d5bc2045d5ac63979",
          "sha1": "57945616529895d9bbee3b1b15612ab8923acf86",
          "md5": "11df0b5493caf63acea5b9b0d4b6431b"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "task-viewer-android-sources.jar",
          "url": "task-viewer-android-6.0.5-sources.jar",
          "size": 20400,
          "sha512": "a28e96f8ebf05b3a13192397d4ffbf01e2446ef7947d47cc1ec698b762c98e1e1edc61e7ec5b8dcee759eef003b9b88fb8651df2e3c5685d3737cd006331a60e",
          "sha256": "9d13bbf45ba189cb694bf92b8c120d47159708b70584753a63620fb161c2aeae",
          "sha1": "d1339824dedbc4ffbdeef0a40bed3e5859d236f4",
          "md5": "9808c073aa74e072c63ea98bffcc71ff"
        }
      ]
    }
  ]
}
