{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-metadata.jar",
          "url": "task-viewer-5.0.1.jar",
          "size": 7937,
          "sha512": "38c6084c90d1a85e24e5728325badc6382e46413c8bcf3911a4f60da8a074e54328e560fffe75fc4bb14a0906296015b4103268a331f1538bf95923cd17cb37a",
          "sha256": "93af152797d4384e5f3eed2d8e33cc3f8a1d2c89ed3234055bffc5ff26caa2ae",
          "sha1": "0d742f90cdcd25bc1448acc2fba9056d059cc137",
          "md5": "cc58fee1baeea48857d930d4c1a873f7"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "task-viewer-kotlin-sources.jar",
          "url": "task-viewer-5.0.1-sources.jar",
          "size": 7737,
          "sha512": "6fbc513b92dd7b1192e526732e1b8f27d7da90fe01a45ad0d8ccd5d59e2295bd0d57843d32afbddf771d4ffbbd440e6a6359d8ac5ecb0bbedc1ac91f996920d7",
          "sha256": "a390d577517443d693833cb17a3d74cf9bdf0b6bb8310d7fe562c0ded71263ad",
          "sha1": "0c3522f3d689b94074837919f5fef656ad85e103",
          "md5": "86d6d0444327fc64e985b40bba082d48"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../task-viewer-android/5.0.1/task-viewer-android-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-android",
        "version": "5.0.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../task-viewer-android/5.0.1/task-viewer-android-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-android",
        "version": "5.0.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../task-viewer-android/5.0.1/task-viewer-android-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-android",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/5.0.1/task-viewer-iosarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/5.0.1/task-viewer-iosarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/5.0.1/task-viewer-iosarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/5.0.1/task-viewer-iosarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/5.0.1/task-viewer-iossimulatorarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/5.0.1/task-viewer-iossimulatorarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/5.0.1/task-viewer-iossimulatorarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/5.0.1/task-viewer-iossimulatorarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../task-viewer-jvm/5.0.1/task-viewer-jvm-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-jvm",
        "version": "5.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../task-viewer-jvm/5.0.1/task-viewer-jvm-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-jvm",
        "version": "5.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../task-viewer-jvm/5.0.1/task-viewer-jvm-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-jvm",
        "version": "5.0.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/5.0.1/task-viewer-wasm-js-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "5.0.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/5.0.1/task-viewer-wasm-js-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "5.0.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/5.0.1/task-viewer-wasm-js-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "5.0.1"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/5.0.1/task-viewer-wasm-js-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "5.0.1"
      }
    }
  ]
}
