[versions]

# mflisar
lumberjack =                    "7.1.1"
kotpreferences =                "0.7.0"
composethemer =                 "0.4.0"
composecolors =                 "1.0.1"

# aurora
aurora =                        "2.0-SNAPSHOT"

[libraries]

# mflisar
lumberjack-core =                       { module = "io.github.mflisar.lumberjack:core", 		                version.ref = "lumberjack" }
lumberjack-implementation-lumberjack =  { module = "io.github.mflisar.lumberjack:implementation-lumberjack",    version.ref = "lumberjack" }
lumberjack-logger-console =             { module = "io.github.mflisar.lumberjack:logger-console",               version.ref = "lumberjack" }
lumberjack-logger-file =                { module = "io.github.mflisar.lumberjack:logger-file",                  version.ref = "lumberjack" }
lumberjack-composeviewer =              { module = "io.github.mflisar.lumberjack:extension-composeviewer",      version.ref = "lumberjack" }
kotpreferences-core =                   { module = "io.github.mflisar.kotpreferences:core", 		            version.ref = "kotpreferences" }
kotpreferences-datastore =              { module = "io.github.mflisar.kotpreferences:storage-datastore", 	    version.ref = "kotpreferences" }
kotpreferences-compose =                { module = "io.github.mflisar.kotpreferences:extension-compose", 	    version.ref = "kotpreferences" }
composethemer-core =                    { module = "io.github.mflisar.composethemer:core", 			            version.ref = "composethemer" }
composethemer-themes =                  { module = "io.github.mflisar.composethemer:themes", 	                version.ref = "composethemer" }
composecolors-material =                { module = "io.github.mflisar.composecolors:material", 	                version.ref = "composecolors" }
composecolors-x11 =                     { module = "io.github.mflisar.composecolors:x11", 	                    version.ref = "composecolors" }
composecolors-material-palette =        { module = "io.github.mflisar.composecolors:material-palette", 	        version.ref = "composecolors" }
composecolors-x11-palette =             { module = "io.github.mflisar.composecolors:x11-palette", 	            version.ref = "composecolors" }

# aurora
aurora-theming =                        { module = "org.pushing-pixels:aurora-theming", 	                    version.ref = "aurora" }
aurora-component =                      { module = "org.pushing-pixels:aurora-component", 	                    version.ref = "aurora" }
aurora-window =                         { module = "org.pushing-pixels:aurora-window", 	                        version.ref = "aurora" }
