[versions]

material =                      "1.12.0"

# mflisar
lumberjack =                    "7.1.1"
kotpreferences =                "0.7.1"
composethemer =                 "0.4.1"
composecolors =                 "1.0.1"

# Windows UI
jewel =                         "0.27.0"
intellij-platform =             "243.21565.208"

[libraries]

material =                              { module = "com.google.android.material:material", 	                        version.ref = "material" }

# mflisar
lumberjack-core =                       { module = "io.github.mflisar.lumberjack:core", 		                version.ref = "lumberjack" }
lumberjack-implementation-lumberjack =  { module = "io.github.mflisar.lumberjack:implementation-lumberjack",    version.ref = "lumberjack" }
lumberjack-logger-console =             { module = "io.github.mflisar.lumberjack:logger-console",               version.ref = "lumberjack" }
lumberjack-logger-file =                { module = "io.github.mflisar.lumberjack:logger-file",                  version.ref = "lumberjack" }
lumberjack-composeviewer =              { module = "io.github.mflisar.lumberjack:extension-composeviewer",      version.ref = "lumberjack" }
kotpreferences-core =                   { module = "io.github.mflisar.kotpreferences:core", 		            version.ref = "kotpreferences" }
kotpreferences-datastore =              { module = "io.github.mflisar.kotpreferences:storage-datastore", 	    version.ref = "kotpreferences" }
kotpreferences-compose =                { module = "io.github.mflisar.kotpreferences:extension-compose", 	    version.ref = "kotpreferences" }
composethemer-core =                    { module = "io.github.mflisar.composethemer:core", 			            version.ref = "composethemer" }
composethemer-themes =                  { module = "io.github.mflisar.composethemer:themes", 	                version.ref = "composethemer" }
composecolors-material =                { module = "io.github.mflisar.composecolors:material", 	                version.ref = "composecolors" }
composecolors-x11 =                     { module = "io.github.mflisar.composecolors:x11", 	                    version.ref = "composecolors" }
composecolors-material-palette =        { module = "io.github.mflisar.composecolors:material-palette", 	        version.ref = "composecolors" }
composecolors-x11-palette =             { module = "io.github.mflisar.composecolors:x11-palette", 	            version.ref = "composecolors" }

# Windows UI
jewel-int-ui-standalone =               { module = "org.jetbrains.jewel:jewel-int-ui-standalone-243",           version.ref = "jewel" }
jewel-int-ui-decorated-window =         { module = "org.jetbrains.jewel:jewel-int-ui-decorated-window-243",     version.ref = "jewel" }
intellij-platform-icons =               { module = "com.jetbrains.intellij.platform:icons",                     version.ref = "intellij-platform" }
