{
  "formatVersion": "1.1",
  "component": {
    "url": "../../task-viewer/5.0.1/task-viewer-5.0.1.module",
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer.aar",
          "url": "task-viewer-android-5.0.1.aar",
          "size": 67692,
          "sha512": "60a64b06f759c5475fdfed99907cafa72f80febfe47fd9c4adf999c1cf8b9e0959e02afd4a56db6440d6f5f30a3e7c4223a0f966e630a7dae29e43ba81ae0496",
          "sha256": "b042dbc30250e5fcd3836b74e025086c453c68c9c2662963477895233f7704a2",
          "sha1": "5fb96ed7938af5747df9d07643b7c521d9be0f50",
          "md5": "78fa29d0c966a9ed2fb6d4338be23a0e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer.aar",
          "url": "task-viewer-android-5.0.1.aar",
          "size": 67692,
          "sha512": "60a64b06f759c5475fdfed99907cafa72f80febfe47fd9c4adf999c1cf8b9e0959e02afd4a56db6440d6f5f30a3e7c4223a0f966e630a7dae29e43ba81ae0496",
          "sha256": "b042dbc30250e5fcd3836b74e025086c453c68c9c2662963477895233f7704a2",
          "sha1": "5fb96ed7938af5747df9d07643b7c521d9be0f50",
          "md5": "78fa29d0c966a9ed2fb6d4338be23a0e"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "task-viewer-android-sources.jar",
          "url": "task-viewer-android-5.0.1-sources.jar",
          "size": 7737,
          "sha512": "6fbc513b92dd7b1192e526732e1b8f27d7da90fe01a45ad0d8ccd5d59e2295bd0d57843d32afbddf771d4ffbbd440e6a6359d8ac5ecb0bbedc1ac91f996920d7",
          "sha256": "a390d577517443d693833cb17a3d74cf9bdf0b6bb8310d7fe562c0ded71263ad",
          "sha1": "0c3522f3d689b94074837919f5fef656ad85e103",
          "md5": "86d6d0444327fc64e985b40bba082d48"
        }
      ]
    }
  ]
}
