{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil/6.0.1/coil-6.0.1.module",
    "group": "io.github.mflisar.toolbox",
    "module": "coil",
    "version": "6.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "coil-iosArm64Main.klib",
          "url": "coil-iosarm64-6.0.1.klib",
          "size": 43259,
          "sha512": "33ff056625ea3ce87988743df4d51f3c6789b88ebef1c0366ec5fbcd87e26476c9ece5ef480fa8a378525284bf82bc86600f61903e9a5318a8f28dc8d611e5a1",
          "sha256": "679188617962336677bf025a21f5e7e32f24a7dba9c4efd4aad7a435e785cc57",
          "sha1": "ac7c24d0da8387b1cf74725eeb96a4f1a55ea3ee",
          "md5": "cca75f75a87370befc22efd428c6cd76"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-iosarm64-sources.jar",
          "url": "coil-iosarm64-6.0.1-sources.jar",
          "size": 8323,
          "sha512": "38d7b64dc1f489bed17f2f3f86f14ff94916f84258132670f48f7aefd578709b832e0c5c01b8790846d3d97bb8dc418a5fb1a30d0c8438cfa96a4faf65536d26",
          "sha256": "1629baa8ec230e65d6a05d4f24a8eb0fec2e99ed247813a40ce1172d369d2164",
          "sha1": "81efcc244f1af3e35f0a848dcde96c590edd93a5",
          "md5": "4899fd1655fbed3369e73336f868a8d8"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "coil.kotlin_resources.zip",
          "url": "coil-iosarm64-6.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "71bab0f7c96c8b1164c26a4afb01ef22bc677a62dc0e422a745cd91b849d8b1f1fcfb705afe38bf4a589f92365e766ffc7d456593a04f7f9b406854ab5574f12",
          "sha256": "9be98d12cc0d5f20992efeed3a71edfc34d42d6d011b3676f1bcb9c9d2eaed11",
          "sha1": "5214d875c1d7067d01d352aa1a808dc353786de3",
          "md5": "d8ecf995e362fd61ae7a093f1e80a79e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "coil-iosarm64-metadata.jar",
          "url": "coil-iosarm64-6.0.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
