{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mflisar.toolbox",
    "module": "ui-adaptive",
    "version": "6.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "ui-adaptive-metadata.jar",
          "url": "ui-adaptive-6.0.6.jar",
          "size": 13758,
          "sha512": "cdc3ae9ab7399d3a9265d4359af4d5908003f18813db33d3f9df2ded198bb41b067d7847cc2d1c7ef5c1d6520b82fa48965b72193724247c918ead6420e08a33",
          "sha256": "5a933ee6590df822d1847ec09656d68c0d1b3882fb8499473cb5538d5e5c6ae7",
          "sha1": "599990c9f21edebe63693712d75e438c2146cc97",
          "md5": "dd287f5ddb7850fec706ab0e1f49c000"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ui-adaptive-kotlin-sources.jar",
          "url": "ui-adaptive-6.0.6-sources.jar",
          "size": 13364,
          "sha512": "9bd5c7da54e954f45dc12439694c8ba164b9b0e270f9695f7e394b1c9c552c09d5277737972556ae4d816c360073a6a2a443953670149d3195251a16d3e4c98a",
          "sha256": "f5ba2633ad142d59e4464f438a730d2bfab0dd1d6dbaf1b3c4d2d4faefddf238",
          "sha1": "2e865e0c2bdf9cb34d3f2daa6841460798fbfac6",
          "md5": "b3ef49434aa4ceab43b3c9ce40caa473"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-adaptive-android/6.0.6/ui-adaptive-android-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-android",
        "version": "6.0.6"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-adaptive-android/6.0.6/ui-adaptive-android-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-android",
        "version": "6.0.6"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-adaptive-android/6.0.6/ui-adaptive-android-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-android",
        "version": "6.0.6"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-adaptive-iosarm64/6.0.6/ui-adaptive-iosarm64-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-iosarm64",
        "version": "6.0.6"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-adaptive-iosarm64/6.0.6/ui-adaptive-iosarm64-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-iosarm64",
        "version": "6.0.6"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-adaptive-iosarm64/6.0.6/ui-adaptive-iosarm64-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-iosarm64",
        "version": "6.0.6"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-adaptive-iosarm64/6.0.6/ui-adaptive-iosarm64-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-iosarm64",
        "version": "6.0.6"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-adaptive-iossimulatorarm64/6.0.6/ui-adaptive-iossimulatorarm64-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-iossimulatorarm64",
        "version": "6.0.6"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-adaptive-iossimulatorarm64/6.0.6/ui-adaptive-iossimulatorarm64-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-iossimulatorarm64",
        "version": "6.0.6"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-adaptive-iossimulatorarm64/6.0.6/ui-adaptive-iossimulatorarm64-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-iossimulatorarm64",
        "version": "6.0.6"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-adaptive-iossimulatorarm64/6.0.6/ui-adaptive-iossimulatorarm64-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-iossimulatorarm64",
        "version": "6.0.6"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-adaptive-jvm/6.0.6/ui-adaptive-jvm-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-jvm",
        "version": "6.0.6"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-adaptive-jvm/6.0.6/ui-adaptive-jvm-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-jvm",
        "version": "6.0.6"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-adaptive-jvm/6.0.6/ui-adaptive-jvm-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-jvm",
        "version": "6.0.6"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ui-adaptive-wasm-js/6.0.6/ui-adaptive-wasm-js-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-wasm-js",
        "version": "6.0.6"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ui-adaptive-wasm-js/6.0.6/ui-adaptive-wasm-js-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-wasm-js",
        "version": "6.0.6"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ui-adaptive-wasm-js/6.0.6/ui-adaptive-wasm-js-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-wasm-js",
        "version": "6.0.6"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ui-adaptive-wasm-js/6.0.6/ui-adaptive-wasm-js-6.0.6.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-adaptive-wasm-js",
        "version": "6.0.6"
      }
    }
  ]
}
