{
  "formatVersion": "1.1",
  "component": {
    "url": "../../proversion/6.0.3/proversion-6.0.3.module",
    "group": "io.github.mflisar.toolbox",
    "module": "proversion",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "proversion.aar",
          "url": "proversion-android-6.0.3.aar",
          "size": 68167,
          "sha512": "954afaea8ec9b3091a226d9b1ad912fd2765019f23552d3792f4347cbab7e8726e37561801a9d5e1570141ef96a1fc7b1b22ac59c91c496eda6fad1ebf518da8",
          "sha256": "425ccb33a833036ae83a03aacc7a197a1531307ef84edc2eef7f1b17f4b9b697",
          "sha1": "08bd9d018aab06bf48907bbd1580487d82319ac0",
          "md5": "375a6d483ec5fb9f44be86e7f8e63f39"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.github.hyochan.openiap",
          "module": "openiap-google",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.hyochan",
          "module": "kmp-iap",
          "version": {
            "requires": "3.5.0"
          },
          "attributes": {
            "com.android.build.api.attributes.ProductFlavor:platform": "play"
          }
        }
      ],
      "files": [
        {
          "name": "proversion.aar",
          "url": "proversion-android-6.0.3.aar",
          "size": 68167,
          "sha512": "954afaea8ec9b3091a226d9b1ad912fd2765019f23552d3792f4347cbab7e8726e37561801a9d5e1570141ef96a1fc7b1b22ac59c91c496eda6fad1ebf518da8",
          "sha256": "425ccb33a833036ae83a03aacc7a197a1531307ef84edc2eef7f1b17f4b9b697",
          "sha1": "08bd9d018aab06bf48907bbd1580487d82319ac0",
          "md5": "375a6d483ec5fb9f44be86e7f8e63f39"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "proversion-android-sources.jar",
          "url": "proversion-android-6.0.3-sources.jar",
          "size": 7420,
          "sha512": "2e2293dfd2440e189feb8526e338afdbc6863cd23808020b374f07d130d6739b18e5d410158365c9096dff3ea66873f24f53f90722ee35275e139b2da884c87d",
          "sha256": "3884484c5575fb789d0bc8e3ab09709036332ee3a378367e30ea3ad4ae636bbe",
          "sha1": "302c8ec46ae6aa1940eb803fc08497117145ac48",
          "md5": "16911b6069b235347df5c7dde368b154"
        }
      ]
    }
  ]
}
