{
  "formatVersion": "1.1",
  "component": {
    "url": "../../app-shared/6.0.0/app-shared-6.0.0.module",
    "group": "io.github.mflisar.toolbox",
    "module": "app-shared",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-file",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "storage-datastore",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-navigator",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-transitions",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-screenmodel",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui-adaptive",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "backup",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-console",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "extension-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared-jvm.jar",
          "url": "app-shared-jvm-6.0.0.jar",
          "size": 907959,
          "sha512": "e11e1cdc0732eb9290a924897e8a453a3e0357a8e22450a49bbe7417b854b7a045c6b331d1deac58b8e071fdd060221bf51261e5b045faba36a5b70bb9413a42",
          "sha256": "a01be7fb6bcd5da3a956df9ced73cc094f21029fc460769be328f9ce4d6b9509",
          "sha1": "b9943ac7908d136da5342f621a597ff5748f4219",
          "md5": "fc05107ab25ba45215e38ecda132f081"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-file",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "storage-datastore",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-navigator",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-transitions",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-screenmodel",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui-adaptive",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "backup",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-console",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "extension-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "extension-composeviewer",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-lumberjack",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "br.com.devsrsouza.compose.icons",
          "module": "font-awesome",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "renderer-header",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "statesaver-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-time",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-bool",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-list",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-button",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "kotpreferences",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composecolors",
          "module": "material",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-picker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-defaultpicker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-jvm.jar",
          "url": "app-shared-jvm-6.0.0.jar",
          "size": 907959,
          "sha512": "e11e1cdc0732eb9290a924897e8a453a3e0357a8e22450a49bbe7417b854b7a045c6b331d1deac58b8e071fdd060221bf51261e5b045faba36a5b70bb9413a42",
          "sha256": "a01be7fb6bcd5da3a956df9ced73cc094f21029fc460769be328f9ce4d6b9509",
          "sha1": "b9943ac7908d136da5342f621a597ff5748f4219",
          "md5": "fc05107ab25ba45215e38ecda132f081"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "shared-jvm-sources.jar",
          "url": "app-shared-jvm-6.0.0-sources.jar",
          "size": 123145,
          "sha512": "b096585d2c795fd3f12c0b4de8d69e654c67f03ca028a8629d665d6994f5c314c98562d02d7a644b827368f3a318e9232e43e864025e515c016884087abfd241",
          "sha256": "8d25b6819f588bd8385a1c7b944a5e89f8c863fe59a406109dd64ff087c172ae",
          "sha1": "ce24fc020a7213a1aa9876269561240441da6b07",
          "md5": "841efa9e827dcf59d7eccb87cf1a0027"
        }
      ]
    }
  ]
}
