{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mflisar.toolbox",
    "module": "task-viewer",
    "version": "6.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.4"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.4"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "task-viewer-metadata.jar",
          "url": "task-viewer-6.0.4.jar",
          "size": 15458,
          "sha512": "e0b575901276214b5f70448e4fb948503bd2ae5ee69a1cb582067cec89ba2354ea2c59d7cfe7aec12426cdcfe069c0f326f8b5413d5febe6e06bba75b1fa1b42",
          "sha256": "763e58cf4ea8a2abe7c5fe4b8909aeb234ff95f9018183db1415f317906da7aa",
          "sha1": "077357ad99f3a9bcea915efe0e889253c60f3245",
          "md5": "6b9c553f6ab226b2108bd2f00e165a81"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "task-viewer-kotlin-sources.jar",
          "url": "task-viewer-6.0.4-sources.jar",
          "size": 16991,
          "sha512": "f812f84d4f3eb508a73dac319679ceaf2dceb7c76b505f909b3a6abe976ad5cbc38e514de51db1c4ab514f1092b5e4beb73f7a84cee8bd2d6e00be151e68397c",
          "sha256": "4c0630e7af7b9ab8482d4c5a1e52d2774f0a36ced12328999a79156ff265741c",
          "sha1": "7a3f7c37f931d1ddf5b7bb2fc3deee4ae8eb1a6d",
          "md5": "866f35fd5fba14c2a87df7dff653804a"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../task-viewer-android/6.0.4/task-viewer-android-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-android",
        "version": "6.0.4"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../task-viewer-android/6.0.4/task-viewer-android-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-android",
        "version": "6.0.4"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../task-viewer-android/6.0.4/task-viewer-android-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-android",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/6.0.4/task-viewer-iosarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/6.0.4/task-viewer-iosarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/6.0.4/task-viewer-iosarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iosarm64/6.0.4/task-viewer-iosarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iosarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/6.0.4/task-viewer-iossimulatorarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/6.0.4/task-viewer-iossimulatorarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/6.0.4/task-viewer-iossimulatorarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../task-viewer-iossimulatorarm64/6.0.4/task-viewer-iossimulatorarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-iossimulatorarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../task-viewer-jvm/6.0.4/task-viewer-jvm-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-jvm",
        "version": "6.0.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../task-viewer-jvm/6.0.4/task-viewer-jvm-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-jvm",
        "version": "6.0.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../task-viewer-jvm/6.0.4/task-viewer-jvm-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-jvm",
        "version": "6.0.4"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/6.0.4/task-viewer-wasm-js-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "6.0.4"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/6.0.4/task-viewer-wasm-js-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "6.0.4"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/6.0.4/task-viewer-wasm-js-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "6.0.4"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../task-viewer-wasm-js/6.0.4/task-viewer-wasm-js-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "task-viewer-wasm-js",
        "version": "6.0.4"
      }
    }
  ]
}
