{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mflisar.toolbox",
    "module": "backup",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "backup-metadata.jar",
          "url": "backup-5.0.1.jar",
          "size": 11276,
          "sha512": "9df52b853c45f927902575ab36a2b7d5093d9483732db0dba6c0a12cd307501cbdcbe2fe75b3f68bf24dab7b4edde86b994abc24778ba091207869cc4bc52b9b",
          "sha256": "e1a290f8165aca20c304249148242aa4ef2e388d26428dde7e89f75a875df78b",
          "sha1": "5a74d5aaddd1009bf36313804273f1f711f5280a",
          "md5": "745198a6f25490776b1b66e25ab6f131"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "backup-kotlin-sources.jar",
          "url": "backup-5.0.1-sources.jar",
          "size": 10519,
          "sha512": "ece5f3aac875e9ea89c41dead95be90c370aa63b41a4791699e17c95d9e78cf19b60d6de688e2f205fdcfb54ee443bc92278a85962b9ff00be69786278856395",
          "sha256": "aedd27083ef23d609d959e39b57120d800f6c2a296aded6bc5d50146f1f3108a",
          "sha1": "49a701c360e6adab4a3f9c65ddfd156342eabc5b",
          "md5": "ecc5283dc02359689594fdae6d50d673"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../backup-android/5.0.1/backup-android-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-android",
        "version": "5.0.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../backup-android/5.0.1/backup-android-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-android",
        "version": "5.0.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../backup-android/5.0.1/backup-android-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-android",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../backup-iosarm64/5.0.1/backup-iosarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-iosarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../backup-iosarm64/5.0.1/backup-iosarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-iosarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../backup-iosarm64/5.0.1/backup-iosarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-iosarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../backup-iosarm64/5.0.1/backup-iosarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-iosarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../backup-iossimulatorarm64/5.0.1/backup-iossimulatorarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-iossimulatorarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../backup-iossimulatorarm64/5.0.1/backup-iossimulatorarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-iossimulatorarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../backup-iossimulatorarm64/5.0.1/backup-iossimulatorarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-iossimulatorarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../backup-iossimulatorarm64/5.0.1/backup-iossimulatorarm64-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-iossimulatorarm64",
        "version": "5.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../backup-jvm/5.0.1/backup-jvm-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-jvm",
        "version": "5.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../backup-jvm/5.0.1/backup-jvm-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-jvm",
        "version": "5.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../backup-jvm/5.0.1/backup-jvm-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-jvm",
        "version": "5.0.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../backup-wasm-js/5.0.1/backup-wasm-js-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-wasm-js",
        "version": "5.0.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../backup-wasm-js/5.0.1/backup-wasm-js-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-wasm-js",
        "version": "5.0.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../backup-wasm-js/5.0.1/backup-wasm-js-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-wasm-js",
        "version": "5.0.1"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../backup-wasm-js/5.0.1/backup-wasm-js-5.0.1.module",
        "group": "io.github.mflisar.toolbox",
        "module": "backup-wasm-js",
        "version": "5.0.1"
      }
    }
  ]
}
