{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/6.0.0/core-6.0.0.module",
    "group": "io.github.mflisar.toolbox",
    "module": "core",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpplatformcontext",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "core-jvm-6.0.0.jar",
          "size": 185544,
          "sha512": "924c5fb600fa452b42357950e4d87f30c95c76da01f3550a5faa4872673fd519263d4f68d6bc4d1dc2d65abdf6b7c5924c64bb6609a8c247548d6060d3303698",
          "sha256": "f604b1de1bf4323acbd12371d7fef11627c0f9ecaf72cb8a6438a5299f993911",
          "sha1": "a2ef4656c2ca11671a19bb745ed316a2e07f7f5e",
          "md5": "319f4f12243304f89bfddc0dd897e263"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpplatformcontext",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "core-jvm-6.0.0.jar",
          "size": 185544,
          "sha512": "924c5fb600fa452b42357950e4d87f30c95c76da01f3550a5faa4872673fd519263d4f68d6bc4d1dc2d65abdf6b7c5924c64bb6609a8c247548d6060d3303698",
          "sha256": "f604b1de1bf4323acbd12371d7fef11627c0f9ecaf72cb8a6438a5299f993911",
          "sha1": "a2ef4656c2ca11671a19bb745ed316a2e07f7f5e",
          "md5": "319f4f12243304f89bfddc0dd897e263"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-sources.jar",
          "url": "core-jvm-6.0.0-sources.jar",
          "size": 39021,
          "sha512": "4c8bf333bb179ae411ec6ea7778bed561514d35b1407fa12b0862bbc4e0dcedcd3a949fa38da2cf93a8dd75a1bdeb6885fddac2a22897e4ea2ac825b3f9167e4",
          "sha256": "e11c4f9df804af2b0988d824fa9cdcc7b804aeb6f5869a0cb7393f1ebef27bb1",
          "sha1": "7341261b588415fd6d3a5a628f9b69469cbbf561",
          "md5": "05d1f28fc4057780b3b52e77b6a9465a"
        }
      ]
    }
  ]
}
