{
  "formatVersion": "1.1",
  "component": {
    "url": "../../table/5.0.0/table-5.0.0.module",
    "group": "io.github.mflisar.toolbox",
    "module": "table",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "table.aar",
          "url": "table-android-5.0.0.aar",
          "size": 265106,
          "sha512": "cc40e5defd49471435e5728078bc01a72e1e539e20014974389a32210922ab4dbd4a012de6fbfecf377320d08bb9097591b3471808c3c23d7dd2462b1abc2c58",
          "sha256": "c0eda456cfbbc4feac5177e010f4767fabc55a7099f4f6f92e19d3a414f46bfd",
          "sha1": "1bd6ed2db47bacf5c8a864145757149c24385950",
          "md5": "8bb05e1007fe94219793dca78539c72c"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "table.aar",
          "url": "table-android-5.0.0.aar",
          "size": 265106,
          "sha512": "cc40e5defd49471435e5728078bc01a72e1e539e20014974389a32210922ab4dbd4a012de6fbfecf377320d08bb9097591b3471808c3c23d7dd2462b1abc2c58",
          "sha256": "c0eda456cfbbc4feac5177e010f4767fabc55a7099f4f6f92e19d3a414f46bfd",
          "sha1": "1bd6ed2db47bacf5c8a864145757149c24385950",
          "md5": "8bb05e1007fe94219793dca78539c72c"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "table-android-sources.jar",
          "url": "table-android-5.0.0-sources.jar",
          "size": 24264,
          "sha512": "39d668c21b66785b227ce8833c02ac245743349632af46aa4f8020148576c37c48eb08726596c97009019626d6d793a0fd95fb2d53a51a1dabeba511faf1c99e",
          "sha256": "dbb5e9d19baad37f94175c8ca35fb4e7dc8899c3e87ec430a3a70ce696032073",
          "sha1": "ba5221f7d2719d6b9d6d09660a086d1e8ce531d7",
          "md5": "26b3c80fc9010443edfec46ee9446f79"
        }
      ]
    }
  ]
}
