{
  "formatVersion": "1.1",
  "component": {
    "url": "../../csv/6.0.3/csv-6.0.3.module",
    "group": "io.github.mflisar.toolbox",
    "module": "csv",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "csv.aar",
          "url": "csv-android-6.0.3.aar",
          "size": 10837,
          "sha512": "78cbe3ef5e67304fe90cbba958cbd379c27712599dad8b004801732b1dd0c562576a6d23885ae96f526a6b89d2b4d404c77e023e8bb7661963bcf95ce689ddde",
          "sha256": "1ffb12bf4427ddedb19e2d5d158c3885cbc3a792f1877f0e0cb95da64988ca4c",
          "sha1": "4880d3a4d5b18d33379fa4dc65193ede3a39e056",
          "md5": "dc54cfc84f2670415db27fceb7a4a869"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "csv.aar",
          "url": "csv-android-6.0.3.aar",
          "size": 10837,
          "sha512": "78cbe3ef5e67304fe90cbba958cbd379c27712599dad8b004801732b1dd0c562576a6d23885ae96f526a6b89d2b4d404c77e023e8bb7661963bcf95ce689ddde",
          "sha256": "1ffb12bf4427ddedb19e2d5d158c3885cbc3a792f1877f0e0cb95da64988ca4c",
          "sha1": "4880d3a4d5b18d33379fa4dc65193ede3a39e056",
          "md5": "dc54cfc84f2670415db27fceb7a4a869"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "csv-android-sources.jar",
          "url": "csv-android-6.0.3-sources.jar",
          "size": 2167,
          "sha512": "23dae2b76a94b0b3df41a60a166f8b8f6a683e393d015a7aa0dff5b5200b075759b0db43ebb0e6b4fe4cea1459153e5cd50f811e7af2cb9992ab4ce9485e3020",
          "sha256": "e3dbc1692c485aa68061bd47dc7c95d88d5b4a6359fd8611513d7de8d7bb3ade",
          "sha1": "86e1027e263272ef0b1388303e97de1db53f78c5",
          "md5": "17a9dbe1e9a673078dda2e1a1e7c3c5b"
        }
      ]
    }
  ]
}
