{
  "formatVersion": "1.1",
  "component": {
    "url": "../../table/5.0.0/table-5.0.0.module",
    "group": "io.github.mflisar.toolbox",
    "module": "table",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "table-jvm.jar",
          "url": "table-jvm-5.0.0.jar",
          "size": 276548,
          "sha512": "736df7ca979839b7e477d497137c49cd7bdf4fd4feeb97df808f1e61a9b9ee27244a214a3beb69e8b565c643dc17560b50618e43714b6cf560094464e4149bd1",
          "sha256": "9b5d117c361406868d96bd5c799833549423cad576f700408a2b6522b74f9d14",
          "sha1": "a568d8e7f73adfd5bde558af42bcb069d4b37d05",
          "md5": "be9ef9e574358e7bf533179daece3b3d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "table-jvm.jar",
          "url": "table-jvm-5.0.0.jar",
          "size": 276548,
          "sha512": "736df7ca979839b7e477d497137c49cd7bdf4fd4feeb97df808f1e61a9b9ee27244a214a3beb69e8b565c643dc17560b50618e43714b6cf560094464e4149bd1",
          "sha256": "9b5d117c361406868d96bd5c799833549423cad576f700408a2b6522b74f9d14",
          "sha1": "a568d8e7f73adfd5bde558af42bcb069d4b37d05",
          "md5": "be9ef9e574358e7bf533179daece3b3d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "table-jvm-sources.jar",
          "url": "table-jvm-5.0.0-sources.jar",
          "size": 24264,
          "sha512": "39d668c21b66785b227ce8833c02ac245743349632af46aa4f8020148576c37c48eb08726596c97009019626d6d793a0fd95fb2d53a51a1dabeba511faf1c99e",
          "sha256": "dbb5e9d19baad37f94175c8ca35fb4e7dc8899c3e87ec430a3a70ce696032073",
          "sha1": "ba5221f7d2719d6b9d6d09660a086d1e8ce531d7",
          "md5": "26b3c80fc9010443edfec46ee9446f79"
        }
      ]
    }
  ]
}
