{
  "formatVersion": "1.1",
  "component": {
    "url": "../../service/6.0.0/service-6.0.0.module",
    "group": "io.github.mflisar.toolbox",
    "module": "service",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "service.aar",
          "url": "service-android-6.0.0.aar",
          "size": 44230,
          "sha512": "04031ec6f66c4165b74e56a62af2e88086fdaff2ea8b691f292006b1172debf78cdba3aef73970756a14f1d1ced107fb62cf851887bdcabab0b924a4551559a5",
          "sha256": "d1496f6cdb3de2cfdc7721230b8356e309d2907defdbc00bd19cfd743b837d70",
          "sha1": "4048d7270d5103bc9620c505f54ff1fbd769ae2d",
          "md5": "c458ee456596be16e190dc897373b40d"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.7.1-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "service.aar",
          "url": "service-android-6.0.0.aar",
          "size": 44230,
          "sha512": "04031ec6f66c4165b74e56a62af2e88086fdaff2ea8b691f292006b1172debf78cdba3aef73970756a14f1d1ced107fb62cf851887bdcabab0b924a4551559a5",
          "sha256": "d1496f6cdb3de2cfdc7721230b8356e309d2907defdbc00bd19cfd743b837d70",
          "sha1": "4048d7270d5103bc9620c505f54ff1fbd769ae2d",
          "md5": "c458ee456596be16e190dc897373b40d"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "service-android-sources.jar",
          "url": "service-android-6.0.0-sources.jar",
          "size": 7093,
          "sha512": "501fe03f4af74b1699d8b20c6ebef67000c07124d03d78f40f7c966bcd0e748632c1866a0efb8577ab96b7dc65b758585e6f090be1548e38131ef65c976c52f5",
          "sha256": "b9b46c1e1430e8e6bfe0a2223945c22c43d4f02f8b6403ff530a9e8a14a2273b",
          "sha1": "1fba8ddaec75829d90b69ef4d0b61c900625bdb2",
          "md5": "8e37977ece8bad04d07a8964f705a4fe"
        }
      ]
    }
  ]
}
