{
  "formatVersion": "1.1",
  "component": {
    "url": "../../backup/6.0.3/backup-6.0.3.module",
    "group": "io.github.mflisar.toolbox",
    "module": "backup",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "backup-iosArm64Main.klib",
          "url": "backup-iosarm64-6.0.3.klib",
          "size": 23109,
          "sha512": "2f4ebd250785c0906040c6f1858c71aa923c68568dbc241efc4930721d36bbbc93159bbc0092e57d415e101e45b7c471527a27160331de22e2358d8ce6df24ac",
          "sha256": "96f0b4fd20d60c9a3ee02ad588d85183e9961bf1724c8e8830862de2a6d27a40",
          "sha1": "67d30bd273c0a760c00f0a7986e5ca35c1e97950",
          "md5": "123d49c9bd16895f1da6bade2c3a8cad"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "backup-iosarm64-sources.jar",
          "url": "backup-iosarm64-6.0.3-sources.jar",
          "size": 7600,
          "sha512": "cd8ec0ae73cf3dfae2538d385a1bdbef36653d44eabc4088b78c6ea58b68bd8d74863089f3055a12274678574bffb6b7399c1263a4c18505161b07cd0cfbe374",
          "sha256": "f0916771de4795e5c6b3e83732cfc86275afe9a3bbf44d916af62f6627f7b24d",
          "sha1": "286e43f03d565a0f46da338dea34503c26f81aab",
          "md5": "e76391b791d131b76f9ed0a44ca92cce"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "backup.kotlin_resources.zip",
          "url": "backup-iosarm64-6.0.3-kotlin_resources.kotlin_resources.zip",
          "size": 348,
          "sha512": "f50e6df58142c4a1d5461931d6ba7c95e99639862edfe5ad27d3df1f2e10b509f8b9e8dc5071a288840525557f3fef008278acf062df5218cedafd87291011ad",
          "sha256": "19da9927ca50ea764cd6b2bd594d935cd37af7a2c96149e032dafac27756c3ca",
          "sha1": "53ea36203fe6c797bf986dc06562caac096ae1bc",
          "md5": "b4caaf036cadbe473d300b1d8d3acd50"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "backup-iosarm64-metadata.jar",
          "url": "backup-iosarm64-6.0.3-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
