{
  "formatVersion": "1.1",
  "component": {
    "url": "../../backup/5.0.0/backup-5.0.0.module",
    "group": "io.github.mflisar.toolbox",
    "module": "backup",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "backup-jvm.jar",
          "url": "backup-jvm-5.0.0.jar",
          "size": 55818,
          "sha512": "7d84f58242f99c1b03aef815e8e283a67103b8b19b91270be497a1bc60a24b10428b2f1d668ee9a2a58979e3702fddd3f96e49206e204695852b3e8666e5f12b",
          "sha256": "a1fb64b1638e4847fe364d9e00338f2201669bdc79eb60b18f96d7aaf69bc044",
          "sha1": "aa65e344422aba72289933467bfbdcc6476a66b6",
          "md5": "7f8fae17ca65cd3483f9b32361e6ecb3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.kmpparcelize",
          "module": "library",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "backup-jvm.jar",
          "url": "backup-jvm-5.0.0.jar",
          "size": 55818,
          "sha512": "7d84f58242f99c1b03aef815e8e283a67103b8b19b91270be497a1bc60a24b10428b2f1d668ee9a2a58979e3702fddd3f96e49206e204695852b3e8666e5f12b",
          "sha256": "a1fb64b1638e4847fe364d9e00338f2201669bdc79eb60b18f96d7aaf69bc044",
          "sha1": "aa65e344422aba72289933467bfbdcc6476a66b6",
          "md5": "7f8fae17ca65cd3483f9b32361e6ecb3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "backup-jvm-sources.jar",
          "url": "backup-jvm-5.0.0-sources.jar",
          "size": 10269,
          "sha512": "7590cb3bd7537b7cce76f0c62af94db49519d91100be10a475041668f92ef4bef9312547a8289e92280726ef806d80bf5526bf84001dd48de1e11c57c56f295a",
          "sha256": "b159c06566b8b4153825b537022cd9e9c959acdf77faa9066fe6e987a04ae5a3",
          "sha1": "71f74efb03b785e05379c6bf00f9219fbd1052f1",
          "md5": "94d25f6a1a605ca243203c56d3ca6a5b"
        }
      ]
    }
  ]
}
