{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mflisar.toolbox",
    "module": "ui",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-metadata.jar",
          "url": "ui-5.0.0.jar",
          "size": 63906,
          "sha512": "63fc1a664a8f8c4e6e99cf8df3954f6817c35f1eb60f4502e30a965309ab8485942d29021fb1d5ae2ac8ead13e3a05966749ac4646fd89b4fcfb864a7370a85e",
          "sha256": "597ca12424f861d3ee95725e523e011cc9740f6962ea84d960652b4294b250f0",
          "sha1": "a56d18734828ccc7f9f01d2a26c4740d692860e1",
          "md5": "5775f4301f6b01a79b2ca0a012864338"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ui-kotlin-sources.jar",
          "url": "ui-5.0.0-sources.jar",
          "size": 81016,
          "sha512": "1c3b051e6a336b00edca62aeb29803eba43a5c73c38c7c9d81719ea2d2fc58a1f307f821af16af2b270cffd7a4055d1f4530c2f6a29af0d955674091c40fec6b",
          "sha256": "ff2afe0db479b24508d9b8e61b01881a7c99cf084e51bd1fb994b2cd7c386334",
          "sha1": "d0c22716df38d72c382509fdfa6128a88324820c",
          "md5": "b2a2189eb6585cebe549099bae3ca5e6"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-android/5.0.0/ui-android-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-android",
        "version": "5.0.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-android/5.0.0/ui-android-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-android",
        "version": "5.0.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-android/5.0.0/ui-android-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-android",
        "version": "5.0.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-iosarm64/5.0.0/ui-iosarm64-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-iosarm64",
        "version": "5.0.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-iosarm64/5.0.0/ui-iosarm64-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-iosarm64",
        "version": "5.0.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-iosarm64/5.0.0/ui-iosarm64-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-iosarm64",
        "version": "5.0.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-iosarm64/5.0.0/ui-iosarm64-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-iosarm64",
        "version": "5.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-iossimulatorarm64/5.0.0/ui-iossimulatorarm64-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-iossimulatorarm64",
        "version": "5.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-iossimulatorarm64/5.0.0/ui-iossimulatorarm64-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-iossimulatorarm64",
        "version": "5.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-iossimulatorarm64/5.0.0/ui-iossimulatorarm64-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-iossimulatorarm64",
        "version": "5.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-iossimulatorarm64/5.0.0/ui-iossimulatorarm64-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-iossimulatorarm64",
        "version": "5.0.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-jvm/5.0.0/ui-jvm-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-jvm",
        "version": "5.0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-jvm/5.0.0/ui-jvm-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-jvm",
        "version": "5.0.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-jvm/5.0.0/ui-jvm-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-jvm",
        "version": "5.0.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ui-wasm-js/5.0.0/ui-wasm-js-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-wasm-js",
        "version": "5.0.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ui-wasm-js/5.0.0/ui-wasm-js-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-wasm-js",
        "version": "5.0.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ui-wasm-js/5.0.0/ui-wasm-js-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-wasm-js",
        "version": "5.0.0"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ui-wasm-js/5.0.0/ui-wasm-js-5.0.0.module",
        "group": "io.github.mflisar.toolbox",
        "module": "ui-wasm-js",
        "version": "5.0.0"
      }
    }
  ]
}
