{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mflisar.toolbox",
    "module": "app-shared",
    "version": "6.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-navigator",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-transitions",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "cafe.adriel.voyager",
          "module": "voyager-screenmodel",
          "version": {
            "requires": "2.2.21-1.10.3"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "core",
          "version": {
            "requires": "6.0.4"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui",
          "version": {
            "requires": "6.0.4"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "ui-adaptive",
          "version": {
            "requires": "6.0.4"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "zip",
          "version": {
            "requires": "6.0.4"
          }
        },
        {
          "group": "io.github.mflisar.toolbox",
          "module": "backup",
          "version": {
            "requires": "6.0.4"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-console",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "extension-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "logger-file",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.kotpreferences",
          "module": "storage-datastore",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "br.com.devsrsouza.compose.icons",
          "module": "font-awesome",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "renderer-header",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composechangelog",
          "module": "statesaver-kotpreferences",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-info",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-time",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedialogs",
          "module": "dialog-frequency",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-bool",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-list",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "screen-button",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composepreferences",
          "module": "kotpreferences",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composecolors",
          "module": "material",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-picker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composethemer",
          "module": "modules-defaultpicker",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.github.vinceglb",
          "module": "filekit-dialogs-compose",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "io.github.mflisar.lumberjack",
          "module": "extension-composeviewer",
          "version": {
            "requires": "12.0.0"
          }
        },
        {
          "group": "io.github.mflisar.composedebugdrawer",
          "module": "plugin-lumberjack",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-metadata.jar",
          "url": "app-shared-6.0.4.jar",
          "size": 92630,
          "sha512": "d86427a945e94789d7eecb76eedc1bacf1e627352c5913ce84f178d5d35e93ac6a8eb4b982f5e7393e6501cb724e752e8d293757b515250bddcaa706e35e1801",
          "sha256": "98ff5522d7dce31b8ad410b178056b8c3265a74d78f1f441594c36e92542862e",
          "sha1": "2f3d8d8359ea26c55c7c6d84a52aaf19f75000cc",
          "md5": "d91a0160df8740fc4ee6cc5443da6b5e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "shared-kotlin-sources.jar",
          "url": "app-shared-6.0.4-sources.jar",
          "size": 110376,
          "sha512": "de7b066aeceef8b8b3a1193287c12aaaab6efdf38f4321807bcd5138e525ae96c10b44e2acfd67a6bb70bfca19099d1e2f8385532cb76b052408388b396aef38",
          "sha256": "16209b1264d53c3962ff7e61884f08e13d950066cd3af0fa07aa2a292510d360",
          "sha1": "e679758dc80b1953f68ad5a507d6367c33be99e4",
          "md5": "2429a9d84583f5fad1c3dc439226d351"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../app-shared-android/6.0.4/app-shared-android-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-android",
        "version": "6.0.4"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../app-shared-android/6.0.4/app-shared-android-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-android",
        "version": "6.0.4"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../app-shared-android/6.0.4/app-shared-android-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-android",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../app-shared-iosarm64/6.0.4/app-shared-iosarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-iosarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../app-shared-iosarm64/6.0.4/app-shared-iosarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-iosarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../app-shared-iosarm64/6.0.4/app-shared-iosarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-iosarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../app-shared-iosarm64/6.0.4/app-shared-iosarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-iosarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../app-shared-iossimulatorarm64/6.0.4/app-shared-iossimulatorarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-iossimulatorarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../app-shared-iossimulatorarm64/6.0.4/app-shared-iossimulatorarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-iossimulatorarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../app-shared-iossimulatorarm64/6.0.4/app-shared-iossimulatorarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-iossimulatorarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../app-shared-iossimulatorarm64/6.0.4/app-shared-iossimulatorarm64-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-iossimulatorarm64",
        "version": "6.0.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../app-shared-jvm/6.0.4/app-shared-jvm-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-jvm",
        "version": "6.0.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../app-shared-jvm/6.0.4/app-shared-jvm-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-jvm",
        "version": "6.0.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../app-shared-jvm/6.0.4/app-shared-jvm-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-jvm",
        "version": "6.0.4"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../app-shared-wasm-js/6.0.4/app-shared-wasm-js-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-wasm-js",
        "version": "6.0.4"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../app-shared-wasm-js/6.0.4/app-shared-wasm-js-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-wasm-js",
        "version": "6.0.4"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../app-shared-wasm-js/6.0.4/app-shared-wasm-js-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-wasm-js",
        "version": "6.0.4"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../app-shared-wasm-js/6.0.4/app-shared-wasm-js-6.0.4.module",
        "group": "io.github.mflisar.toolbox",
        "module": "app-shared-wasm-js",
        "version": "6.0.4"
      }
    }
  ]
}
