name: Publish to GitHub Repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: string

  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    uses: MFlisar/kmp-devtools/.github/workflows/publish-to-github-repository.yml@8.5.0

    with:
      version: ${{ inputs.version }}
      artifactsBranch: published-artifacts